In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import time as t

def isValid(chess,cell):
  row= cell // n
  col= cell % n

  cuadrant_row = (row // sqrt_n) * sqrt_n
  cuadrant_col = (col // sqrt_n) * sqrt_n

  #check row
  for i in range(n):
    if (i != col) and (chess[row][i]== 1):
      return False
  #check column
  for i in range(n):
    if (i != row) and (chess[i][col]== 1):
      return False
  #check diagonal
  if check_diagonals(chess,row,col)==True and check_diagonals2(chess,row,col)==True:
    return True 
  else:
    return False

def check_diagonals(chess,row,column):
  for c in range(column,n):
    if c+row >= n:
      break
    if chess[c+row][c]==1:
      return False

  for c in range(column,-1,-1):
    if row-c < 0:
      break
    if chess[row-c][c]==1:
      return False
  return True

def check_diagonals2(chess,row,column):
  for c in range(column,n):
    if c+row >= n:
      break
    if chess[c][c+row]==1:
      return False

  for c in range(column,-1,-1):
    if row-c < 0:
      break
    if chess[c][row-c]==1:
      return False
  return True

    
def chess_solver(chess,cell,count):
  row= cell // n
  col= cell % n

  if count == 8:
    return True
  if cell >= n**2:
    return False 

  if isValid(chess,cell):
      chess[row][col]=1
      if chess_solver(chess,cell+1,count+1):
        return True
      else:
        chess[row][col]=0

  return chess_solver(chess,cell+1,count)
   


n=8
sqrt_n= int(n**0.5)
chess= [[0 for col in range(n)]for row in range(n)]
chess_solver(chess,0,0)
print(np.matrix(chess))


[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1]]
